import test from 'node:test'
import assert from 'node:assert/strict'
import { chromium, expect } from '@playwright/test'
import { mkdir, readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

// Run against `node tests/lorelink/serve.mjs` ONLY. Browser -> HTTP shim ->
// production Lorelink SQL -> disk-backed PGlite. Supabase Auth/Storage are not live.
const origin='http://127.0.0.1:5176',backend='http://127.0.0.1:9179'
const personal=process.env.LORELINK_PLAYER_QA==='1'
const characterId='10000000-0000-4000-8000-000000000002'
const version=personal?'v2':'v1'
const historyUrl=`${origin}/app/history${personal?`?character=${characterId}`:''}`
const shots=process.env.LORELINK_SCREENSHOTS ?? join(tmpdir(),'lorelink-browser-evidence')
test('browser: História integrated flow against isolated PostgreSQL',async t=>{
  await mkdir(shots,{recursive:true})
  const browser=await chromium.launch({channel:'msedge',headless:true})
  const context=await browser.newContext({viewport:{width:1440,height:960}})
  const page=await context.newPage()
  await page.request.post(`${backend}/__test/reset`)
  t.after(async()=>{ await page.screenshot({path:join(shots,'qa-last-state.png')}).catch(()=>{}); await browser.close() })
  const step = async (name, action) => {
    let failure
    await t.test(name, async () => { try { await action() } catch (error) { failure=error; console.error(error.message); throw error } })
    if(failure)throw failure
  }
  const errors=[]
  page.on('pageerror',error=>errors.push(error.message))
  await page.goto(origin)
  await page.getByLabel(/^email$/i).fill(personal?'player@example.test':'gm@example.test')
  await page.getByLabel(/^palavra-passe$/i).fill('test-only')
  const tokenResponse=page.waitForResponse(r=>r.url().includes('/auth/v1/token')&&r.status()===200)
  const profileReady=page.waitForResponse(r=>r.url().includes('/rest/v1/profiles')&&r.status()===200)
  await page.getByRole('button',{name:/entrar no arquivo/i}).click()
  const token=(await (await tokenResponse).json()).access_token
  await profileReady
  await page.goto(historyUrl)
  await expect(page.getByRole('heading',{name:'História',exact:true})).toBeVisible()
  const call=async (name,args={})=>{
    const response=await page.request.post(`${backend}/rest/v1/rpc/${name}`,{headers:{Authorization:`Bearer ${token}`},data:args})
    if(!response.ok())throw new Error(JSON.stringify(await response.json()))
    return response.json()
  }
  const read=()=>call(`lorelink_read_${version}`,{expected_scope:'veil',...(personal?{requested_character:characterId}:{})})
  const saved=()=>expect(page.locator('.lore-save')).toHaveText('Guardado',{timeout:10000})
  const suffix=Date.now().toString().slice(-6),nameA=`Personagem QA ${suffix}`,nameB=`Evento QA ${suffix}`
  let a,b,relationId
  const create=async(name,kind)=>{
    await page.getByRole('button',{name:'Criar',exact:true}).click()
    const dialog=page.getByRole('dialog',{name:'Criar ficha',exact:true})
    await dialog.getByLabel('Nome da nova ficha').fill(name)
    await dialog.getByLabel('Tipo da nova ficha').selectOption(kind)
    await dialog.getByRole('button',{name:'Criar ficha',exact:true}).click()
    await saved()
    return (await read()).entities.find(e=>e.name===name)
  }
  await step('create, write, reload; editor expands; Markdown HTML/unsafe links are inert',async()=>{
    a=await create(nameA,'person')
    await page.getByLabel('Resumo',{exact:true}).fill('Conteúdo sintético para testes isolados.')
    await page.getByPlaceholder('Escreve livremente a história desta ficha…').fill('## História de teste\n\nTexto livre e longo.\n\n<script>window.__lore_xss=1</script>\n\n[malicioso](javascript:alert(1))')
    await page.getByRole('button',{name:'Expandir editor'}).click()
    await expect(page.locator('.lore-editor--expanded')).toBeVisible()
    await page.getByRole('button',{name:'Formatted preview'}).click()
    await expect(page.locator('.net-search-markdown')).toBeVisible()
    assert.equal(await page.evaluate(()=>window.__lore_xss),undefined)
    assert.equal(await page.locator('.net-search-markdown a[href^="javascript:"]').count(),0)
    await page.getByRole('button',{name:'Recolher editor'}).click()
    await saved()
    await page.reload()
    await page.getByRole('button',{name:'Fichas',exact:true}).click()
    await page.locator('.lore-card').filter({hasText:nameA}).click()
    await expect(page.locator('.lore-reader')).toContainText('Texto livre e longo.')
    await expect(page.getByRole('combobox',{name:'Estado',exact:true})).toHaveCount(0)
    await page.getByRole('button',{name:'Editar',exact:true}).click()
    await expect(page.getByPlaceholder('Escreve livremente a história desta ficha…')).toHaveValue(/Texto livre e longo/)
  })
  await step('create, edit and remove directional relation via interface',async()=>{
    b=await create(nameB,'event')
    await page.getByLabel('Data ou período no universo').fill('Antes do inverno 42')
    await page.getByRole('button',{name:'Nova relação',exact:true}).click()
    const dialog=page.getByRole('dialog',{name:'Relação',exact:true})
    await dialog.getByRole('combobox',{name:'Origem',exact:true}).selectOption(a.id)
    await dialog.getByRole('combobox',{name:'Destino',exact:true}).selectOption(b.id)
    await dialog.getByLabel('Nome da relação').fill('participou em')
    await dialog.getByRole('button',{name:'Guardar relação'}).click()
    await saved()
    relationId=(await read()).relations.find(r=>r.source===a.id&&r.target===b.id).id
    await page.locator('.lore-relation-row button').filter({hasText:'participou em'}).click()
    await dialog.getByLabel('Nome da relação').fill('investigou')
    await dialog.getByRole('button',{name:'Guardar relação'}).click()
    await saved();assert.equal((await read()).relations.find(r=>r.id===relationId).label,'investigou')
    await page.locator('.lore-relation-row button').filter({hasText:'investigou'}).click()
    await dialog.getByRole('button',{name:'Remover relação'}).click()
    await saved();assert.ok(!(await read()).relations.some(r=>r.id===relationId))
    // Create a new custom directed relation for the graph checks.
    await page.getByRole('button',{name:'Nova relação',exact:true}).click()
    await dialog.getByRole('combobox',{name:'Origem',exact:true}).selectOption(a.id)
    await dialog.getByRole('combobox',{name:'Destino',exact:true}).selectOption(b.id)
    await dialog.getByLabel('Nome da relação').fill('participou em')
    await dialog.getByRole('button',{name:'Guardar relação'}).click();await saved()
  })
  await step('drag nodes; persisted positions match after reload; selection preserves viewport',async()=>{
    await page.getByRole('button',{name:'Fechar ficha'}).click()
    await page.getByRole('button',{name:'Mapa',exact:true}).click()
    await page.getByRole('button',{name:'Enquadrar tudo'}).click()
    const node=page.locator(`.react-flow__node[data-id="${a.id}"]`)
    await expect(node).toBeVisible()
    const before=(await read()).nodes.find(n=>n.entity_id===a.id)
    const rect=await node.boundingBox()
    await page.mouse.move(rect.x+rect.width/2,rect.y+35)
    await page.mouse.down();await page.mouse.move(rect.x+rect.width/2-150,rect.y+100,{steps:12});await page.mouse.up()
    await saved()
    const after=(await read()).nodes.find(n=>n.entity_id===a.id)
    assert.ok(Math.abs(after.x-before.x)>50)
    await page.reload()
    await expect(page.locator(`.react-flow__node[data-id="${a.id}"]`)).toBeVisible()
    const persisted=(await read()).nodes.find(n=>n.entity_id===a.id)
    assert.equal(persisted.x,after.x);assert.equal(persisted.y,after.y)
    const viewport=await page.locator('.react-flow__viewport').getAttribute('style')
    await page.locator(`.react-flow__node[data-id="${a.id}"]`).click()
    assert.equal(await page.locator('.react-flow__viewport').getAttribute('style'),viewport)
  })
  await step('search, type filter, focus, remove from map while retaining entity',async()=>{
    await page.getByRole('button',{name:'Focar nesta ficha'}).click()
    assert.equal(await page.locator('.react-flow__node').count(),2)
    await page.getByRole('button',{name:'Vista geral',exact:false}).click()
    await page.getByRole('textbox',{name:'Pesquisar fichas'}).fill(nameA)
    await expect(page.locator('.react-flow__node')).toHaveCount(1)
    await page.getByRole('textbox',{name:'Pesquisar fichas'}).fill('')
    await page.getByRole('combobox',{name:'Filtrar por tipo'}).selectOption('event')
    await expect(page.locator(`.react-flow__node[data-id="${a.id}"]`)).toHaveCount(0)
    await page.getByRole('combobox',{name:'Filtrar por tipo'}).selectOption('')
    await page.getByRole('button',{name:'Retirar do mapa'}).click();await saved()
    await expect(page.locator(`.react-flow__node[data-id="${a.id}"]`)).toHaveCount(0)
    await page.getByRole('button',{name:'Fichas',exact:true}).click()
    await expect(page.locator('.lore-card').filter({hasText:nameA})).toBeVisible()
    await page.getByRole('button',{name:'Colocar no mapa'}).click();await saved()
  })
  await step('save failure preserves typing, prevents workspace switch, retries without duplication',async()=>{
    await page.getByRole('button',{name:'Editar',exact:true}).click()
    await page.request.post(`${backend}/__test/fail-next`)
    const editor=page.getByPlaceholder('Escreve livremente a história desta ficha…')
    await editor.fill('Texto que não pode desaparecer após uma falha.')
    await expect(page.locator('.lore-save')).toHaveText('Não foi possível guardar')
    await editor.fill('Texto preservado, com mais palavras escritas durante a falha.')
    assert.equal(await editor.inputValue(),'Texto preservado, com mais palavras escritas durante a falha.')
    await page.request.post(`${backend}/__test/fail-next`)
    if(personal){
      await page.getByRole('link',{name:'Trocar personagem'}).click()
      await page.getByRole('button',{name:'Guardar e sair'}).click()
      await expect(page.getByRole('dialog',{name:'Alterações por guardar'})).toBeVisible()
      await page.getByRole('button',{name:'Continuar a escrever'}).click()
    }else await page.getByRole('combobox',{name:'Universo',exact:true}).selectOption('altara')
    await expect(page.locator('.lore-save')).toHaveText('Não foi possível guardar')
    assert.equal((await call(`lorelink_context_${version}`,personal?{requested_character:characterId}:{})).scope,'veil')
    await page.getByRole('button',{name:'Tentar novamente',exact:true}).click();await saved()
    const data=await read();assert.equal(data.entities.filter(e=>e.id===a.id).length,1)
    assert.equal(data.entities.find(e=>e.id===a.id).body,await editor.inputValue())
  })
  await step('keyboard delete in editor cannot remove graph data; long text late responses preserve latest text',async()=>{
    await page.request.post(`${backend}/__test/delay-next`)
    const editor=page.getByPlaceholder('Escreve livremente a história desta ficha…')
    await editor.fill('Primeira versão em trânsito.')
    await page.waitForRequest(r=>r.url().includes(`lorelink_save_entity_${version}`))
    await editor.fill('Versão mais recente, ainda a escrever.')
    await editor.press('End');await editor.press('Delete');await saved()
    assert.equal((await read()).entities.find(e=>e.id===a.id).body,'Versão mais recente, ainda a escrever.')
    assert.ok((await read()).nodes.some(n=>n.entity_id===a.id&&!n.hidden))
  })
  await step('versions restore privately; archive and recover through UI',async()=>{
    await page.getByRole('button',{name:'Versões anteriores'}).click()
    await expect(page.locator('.lore-revisions details').first()).toBeVisible()
    await page.locator('.lore-revisions summary').first().click()
    page.once('dialog',dialog=>dialog.accept())
    await page.getByRole('button',{name:'Recuperar versão',exact:true}).first().click();await saved()
    assert.equal((await read()).entities.find(e=>e.id===a.id).visibility,'private')
    page.once('dialog',dialog=>dialog.accept())
    await page.getByRole('button',{name:'Arquivar ficha',exact:true}).click();await saved()
    await page.getByRole('button',{name:'Arquivadas',exact:true}).click()
    await page.locator('.lore-card').filter({hasText:nameA}).click()
    await page.getByRole('button',{name:'Editar',exact:true}).click()
    page.once('dialog',dialog=>dialog.accept())
    await page.getByRole('button',{name:'Recuperar ficha',exact:true}).click();await saved()
    assert.equal((await read()).entities.find(e=>e.id===a.id).archived,false)
    await page.getByRole('button',{name:'Arquivadas',exact:true}).click()
  })
  await step('universe changes clear selection and results; data survives return',async()=>{
    if(personal){
      await page.getByRole('link',{name:'Trocar personagem'}).click()
      await page.getByRole('link',{name:/Personagem B/}).click()
      await expect(page.locator('.lore-character-name')).toHaveText('Personagem B')
      await expect(page.locator('.lore-brand')).toContainText('ALTARA')
      await expect(page.locator('.lore-editor')).toHaveCount(0)
      await expect(page.getByText(nameA,{exact:true})).toHaveCount(0)
      await page.getByRole('link',{name:'Trocar personagem'}).click()
      await page.getByRole('link',{name:/Personagem A/}).click()
      await expect(page.locator(`.react-flow__node[data-id="${a.id}"]`)).toBeVisible()
      return
    }
    await page.getByRole('combobox',{name:'Universo',exact:true}).selectOption('altara')
    await expect(page.getByRole('combobox',{name:'Universo',exact:true})).toHaveValue('altara')
    await expect(page.locator('.lore-editor')).toHaveCount(0)
    await expect(page.getByText(nameA,{exact:true})).toHaveCount(0)
    await page.getByRole('combobox',{name:'Universo',exact:true}).selectOption('veil')
    await expect(page.getByRole('combobox',{name:'Universo',exact:true})).toHaveValue('veil')
    await expect(page.locator(`.react-flow__node[data-id="${a.id}"]`)).toBeVisible()
  })
  await step('export confirmed structured data; desktop and narrow-screen evidence',async()=>{
    const downloaded=page.waitForEvent('download')
    await page.getByRole('button',{name:'Exportar',exact:true}).click()
    const file=await downloaded;assert.equal(file.suggestedFilename(),'historia-veil.json')
    await page.getByRole('button',{name:'Enquadrar tudo'}).click()
    await page.screenshot({path:join(shots,'historia-mapa-desktop.png')})
    await page.locator(`.react-flow__node[data-id="${a.id}"]`).click()
    await page.getByRole('button',{name:'Enquadrar tudo'}).click()
    await page.locator('.lore-editor__body').evaluate(el=>{el.scrollTop=0})
    await page.screenshot({path:join(shots,'historia-editor-desktop.png')})
    await page.setViewportSize({width:390,height:844})
    await expect(page.getByRole('button',{name:'Fechar ficha'})).toBeVisible()
    const box=await page.locator('.lore-editor').boundingBox()
    assert.ok(box.x>=0&&box.x+box.width<=391)
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
    await page.getByRole('button',{name:'Editar',exact:true}).click()
    await page.getByPlaceholder('Escreve livremente a história desta ficha…').scrollIntoViewIfNeeded()
    await page.screenshot({path:join(shots,'historia-editor-mobile.png')})
    await page.getByRole('button',{name:'Fechar ficha'}).click()
    await expect(page.locator('.lore-map')).toBeVisible()
    await page.setViewportSize({width:1440,height:960})
  })
  if(personal)await step('changing character while saving waits; same-universe characters do not inherit text',async()=>{
    await page.getByRole('button',{name:'Fichas',exact:true}).click()
    await page.locator('.lore-card').filter({hasText:nameA}).click()
    await page.getByRole('button',{name:'Editar',exact:true}).click()
    await page.request.post(`${backend}/__test/delay-next`)
    const request=page.waitForRequest(r=>r.url().includes('lorelink_save_entity_v2'))
    await page.getByPlaceholder('Escreve livremente a história desta ficha…').fill('Texto da personagem A durante a troca.')
    await request
    await page.getByRole('link',{name:'Trocar personagem'}).click()
    await expect(page.getByRole('dialog',{name:'Alterações por guardar'})).toBeVisible()
    await page.getByRole('button',{name:'Guardar e sair'}).click()
    await page.getByRole('link',{name:/Personagem C/}).click()
    await expect(page.locator('.lore-character-name')).toHaveText('Personagem C')
    await expect(page.locator('.react-flow__node')).toHaveCount(0)
    await page.getByRole('link',{name:'Trocar personagem'}).click()
    await page.getByRole('link',{name:/Personagem A/}).click()
    await page.getByRole('button',{name:'Fichas',exact:true}).click()
    await page.locator('.lore-card').filter({hasText:nameA}).click()
    await page.getByRole('button',{name:'Editar',exact:true}).click()
    await expect(page.getByPlaceholder('Escreve livremente a história desta ficha…')).toHaveValue('Texto da personagem A durante a troca.')
    assert.equal((await read()).entities.find(e=>e.id===a.id).body,'Texto da personagem A durante a troca.')
  })
  if(personal)await step('external universe reassignment hides old data and lets a failed draft be exported before leaving',async()=>{
    await page.request.post(`${backend}/__test/fail-next`)
    await page.getByPlaceholder('Escreve livremente a história desta ficha…').fill('Rascunho privado no universo anterior.')
    await expect(page.locator('.lore-save')).toHaveText('Não foi possível guardar')
    await page.request.post(`${backend}/__test/character-scope`,{data:{character:characterId,scope:'altara'}})
    await page.evaluate(()=>window.dispatchEvent(new Event('focus')))
    await expect(page.getByRole('heading',{name:'O contexto de acesso mudou'})).toBeVisible()
    await expect(page.getByText(nameA,{exact:true})).toHaveCount(0)
    await page.getByRole('link',{name:'Escolher personagem'}).click()
    await expect(page.getByRole('dialog',{name:'Alterações por guardar'})).toBeVisible()
    const downloaded=page.waitForEvent('download')
    await page.getByRole('button',{name:'Exportar rascunho e sair'}).click()
    const file=await downloaded
    const draft=JSON.parse(await readFile(await file.path(),'utf8'))
    assert.equal(draft.data.character_id,characterId)
    assert.equal(draft.data.entities.find(e=>e.id===a.id).body,'Rascunho privado no universo anterior.')
    await page.getByRole('link',{name:/Personagem A/}).click()
    await expect(page.locator('.lore-character-name')).toHaveText('Personagem A')
    await expect(page.locator('.react-flow__node')).toHaveCount(0)
    await expect(page.locator('.lore-brand')).toContainText('ALTARA')
    await page.request.post(`${backend}/__test/character-scope`,{data:{character:characterId,scope:'veil'}})
  })
  await step('anonymous route is guarded; player lands on own character picker without private universe names',async()=>{
    const anon=await browser.newContext(),anonPage=await anon.newPage()
    await anonPage.goto(`${origin}/app/history`)
    await expect(anonPage.getByRole('button',{name:/entrar no arquivo/i})).toBeVisible()
    await anonPage.getByLabel(/^email$/i).fill('player@example.test')
    await anonPage.getByLabel(/^palavra-passe$/i).fill('test-only')
    const playerReady=anonPage.waitForResponse(r=>r.url().includes('/rest/v1/profiles')&&r.status()===200)
    await anonPage.getByRole('button',{name:/entrar no arquivo/i}).click()
    await playerReady
    await anonPage.goto(`${origin}/app/history`)
    await expect(anonPage.getByRole('heading',{name:'História',exact:true})).toBeVisible()
    await expect(anonPage.getByRole('button',{name:'Criar',exact:true})).toHaveCount(0)
    await expect(anonPage.getByRole('link',{name:/Personagem A/})).toBeVisible()
    await expect(anonPage.getByText(nameA,{exact:true})).toHaveCount(0)
    await expect(anonPage.getByText(nameB,{exact:true})).toHaveCount(0)
    await anon.close()
  })
  assert.deepEqual(errors,[],'No browser runtime errors')
})
