import type { NetEvent } from './netWorldTypes'

export const netEvents: readonly NetEvent[] = [
  {
    id: 'event-eastern-industrial-fire',
    title: 'Eastern Industrial District warehouse fire',
    districtId: 'district-eastern-industrial',
    locationId: 'location-eastern-industrial-rail-spur-3',
    participantEntityIds: [],
    participantOrganisationIds: ['org-nvn', 'org-nvps'],
    status: 'developing',
    aliases: ['Eastern Industrial explosion', 'Eastern Industrial fire'],
    topicTags: ['Public Safety', 'Infrastructure'],
  },
  {
    id: 'event-district-04-power-surge',
    title: 'District 04 power surge',
    districtId: 'district-04',
    participantEntityIds: [],
    participantOrganisationIds: ['org-nvps', 'org-netwatch'],
    status: 'reported',
    aliases: ['District 04 outage', 'District04 surge'],
    topicTags: ['Infrastructure', 'Public Safety'],
  },
  {
    id: 'event-neon-row-resonance-spike',
    title: 'Neon Row resonance spike',
    districtId: 'district-neon-row',
    participantEntityIds: [],
    participantOrganisationIds: ['org-lucid'],
    status: 'reported',
    aliases: ['Unexplained resonance spike'],
    topicTags: ['ECHO', 'Resonance'],
  },
  {
    id: 'event-nvps-drone-patrol-expansion',
    title: 'NVPS drone patrol expansion',
    districtId: 'district-07',
    participantEntityIds: [],
    participantOrganisationIds: ['org-nvps'],
    status: 'announced',
    aliases: ['Drone patrol expansion'],
    topicTags: ['Public Safety', 'Surveillance'],
  },
  {
    id: 'event-blackwater-dock-strike',
    title: 'Blackwater dock strike',
    districtId: 'district-blackwater',
    participantEntityIds: [],
    participantOrganisationIds: [],
    status: 'announced',
    aliases: ['Blackwater labour action'],
    topicTags: ['Labour', 'Automation'],
  },
] as const
